export const ADMIN_AUSPICIANTES_REQUEST = "ADMIN_AUSPICIANTES_REQUEST";
export const ADMIN_AUSPICIANTES_SUCCESS = "ADMIN_AUSPICIANTES_SUCCESS";
export const ADMIN_AUSPICIANTES_FAIL = "ADMIN_AUSPICIANTES_FAIL";

export const CREATE_AUSPICIANTE_REQUEST = "CREATE_AUSPICIANTE_REQUEST";
export const CREATE_AUSPICIANTE_SUCCESS = "CREATE_AUSPICIANTE_SUCCESS";
export const CREATE_AUSPICIANTE_RESET = "CREATE_AUSPICIANTE_RESET";
export const CREATE_AUSPICIANTE_FAIL = "CREATE_AUSPICIANTE_FAIL";

export const UPDATE_AUSPICIANTE_REQUEST = "UPDATE_AUSPICIANTE_REQUEST";
export const UPDATE_AUSPICIANTE_SUCCESS = "UPDATE_AUSPICIANTE_SUCCESS";
export const UPDATE_AUSPICIANTE_RESET = "UPDATE_AUSPICIANTE_RESET";
export const UPDATE_AUSPICIANTE_FAIL = "UPDATE_AUSPICIANTE_FAIL";

export const DELETE_AUSPICIANTE_REQUEST = "DELETE_AUSPICIANTE_REQUEST";
export const DELETE_AUSPICIANTE_SUCCESS = "DELETE_AUSPICIANTE_SUCCESS";
export const DELETE_AUSPICIANTE_RESET = "DELETE_AUSPICIANTE_RESET";
export const DELETE_AUSPICIANTE_FAIL = "DELETE_AUSPICIANTE_FAIL";

export const AUSPICIANTE_DETAILS_REQUEST = "AUSPICIANTE_DETAILS_REQUEST";
export const AUSPICIANTE_DETAILS_SUCCESS = "AUSPICIANTE_DETAILS_SUCCESS";
export const AUSPICIANTE_DETAILS_FAIL = "AUSPICIANTE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
