export const ADMIN_CATEGORIAS_REQUEST = "ADMIN_CATEGORIAS_REQUEST";
export const ADMIN_CATEGORIAS_SUCCESS = "ADMIN_CATEGORIAS_SUCCESS";
export const ADMIN_CATEGORIAS_FAIL = "ADMIN_CATEGORIAS_FAIL";

export const CREATE_CATEGORIA_REQUEST = "CREATE_CATEGORIA_REQUEST";
export const CREATE_CATEGORIA_SUCCESS = "CREATE_CATEGORIA_SUCCESS";
export const CREATE_CATEGORIA_RESET = "CREATE_CATEGORIA_RESET";
export const CREATE_CATEGORIA_FAIL = "CREATE_CATEGORIA_FAIL";

export const UPDATE_CATEGORIA_REQUEST = "UPDATE_CATEGORIA_REQUEST";
export const UPDATE_CATEGORIA_SUCCESS = "UPDATE_CATEGORIA_SUCCESS";
export const UPDATE_CATEGORIA_RESET = "UPDATE_CATEGORIA_RESET";
export const UPDATE_CATEGORIA_FAIL = "UPDATE_CATEGORIA_FAIL";

export const DELETE_CATEGORIA_REQUEST = "DELETE_CATEGORIA_REQUEST";
export const DELETE_CATEGORIA_SUCCESS = "DELETE_CATEGORIA_SUCCESS";
export const DELETE_CATEGORIA_RESET = "DELETE_CATEGORIA_RESET";
export const DELETE_CATEGORIA_FAIL = "DELETE_CATEGORIA_FAIL";

export const CATEGORIA_DETAILS_REQUEST = "CATEGORIA_DETAILS_REQUEST";
export const CATEGORIA_DETAILS_SUCCESS = "CATEGORIA_DETAILS_SUCCESS";
export const CATEGORIA_DETAILS_FAIL = "CATEGORIA_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
