export const ADMIN_CLASIFICACIONES_REQUEST = "ADMIN_CLASIFICACIONES_REQUEST";
export const ADMIN_CLASIFICACIONES_SUCCESS = "ADMIN_CLASIFICACIONES_SUCCESS";
export const ADMIN_CLASIFICACIONES_FAIL = "ADMIN_CLASIFICACIONES_FAIL";

export const CREATE_CLASIFICACION_REQUEST = "CREATE_CLASIFICACION_REQUEST";
export const CREATE_CLASIFICACION_SUCCESS = "CREATE_CLASIFICACION_SUCCESS";
export const CREATE_CLASIFICACION_RESET = "CREATE_CLASIFICACION_RESET";
export const CREATE_CLASIFICACION_FAIL = "CREATE_CLASIFICACION_FAIL";

export const UPDATE_CLASIFICACION_REQUEST = "UPDATE_CLASIFICACION_REQUEST";
export const UPDATE_CLASIFICACION_SUCCESS = "UPDATE_CLASIFICACION_SUCCESS";
export const UPDATE_CLASIFICACION_RESET = "UPDATE_CLASIFICACION_RESET";
export const UPDATE_CLASIFICACION_FAIL = "UPDATE_CLASIFICACION_FAIL";

export const DELETE_CLASIFICACION_REQUEST = "DELETE_CLASIFICACION_REQUEST";
export const DELETE_CLASIFICACION_SUCCESS = "DELETE_CLASIFICACION_SUCCESS";
export const DELETE_CLASIFICACION_RESET = "DELETE_CLASIFICACION_RESET";
export const DELETE_CLASIFICACION_FAIL = "DELETE_CLASIFICACION_FAIL";

export const CLASIFICACION_DETAILS_REQUEST = "CLASIFICACION_DETAILS_REQUEST";
export const CLASIFICACION_DETAILS_SUCCESS = "CLASIFICACION_DETAILS_SUCCESS";
export const CLASIFICACION_DETAILS_FAIL = "CLASIFICACION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
