export const ADMIN_CONFIGURACION_REQUEST = "ADMIN_CONFIGURACION_REQUEST";
export const ADMIN_CONFIGURACION_SUCCESS = "ADMIN_CONFIGURACION_SUCCESS";
export const ADMIN_CONFIGURACION_FAIL = "ADMIN_CONFIGURACION_FAIL";

export const UPDATE_CONFIGURACION_REQUEST = "UPDATE_CONFIGURACION_REQUEST";
export const UPDATE_CONFIGURACION_SUCCESS = "UPDATE_CONFIGURACION_SUCCESS";
export const UPDATE_CONFIGURACION_RESET = "UPDATE_CONFIGURACION_RESET";
export const UPDATE_CONFIGURACION_FAIL = "UPDATE_CONFIGURACION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";