export const ADMIN_CONTRATOS_REQUEST = "ADMIN_CONTRATOS_REQUEST";
export const ADMIN_CONTRATOS_SUCCESS = "ADMIN_CONTRATOS_SUCCESS";
export const ADMIN_CONTRATOS_FAIL = "ADMIN_CONTRATOS_FAIL";

export const CREATE_CONTRATO_REQUEST = "CREATE_CONTRATO_REQUEST";
export const CREATE_CONTRATO_SUCCESS = "CREATE_CONTRATO_SUCCESS";
export const CREATE_CONTRATO_RESET = "CREATE_CONTRATO_RESET";
export const CREATE_CONTRATO_FAIL = "CREATE_CONTRATO_FAIL";

export const UPDATE_CONTRATO_REQUEST = "UPDATE_CONTRATO_REQUEST";
export const UPDATE_CONTRATO_SUCCESS = "UPDATE_CONTRATO_SUCCESS";
export const UPDATE_CONTRATO_RESET = "UPDATE_CONTRATO_RESET";
export const UPDATE_CONTRATO_FAIL = "UPDATE_CONTRATO_FAIL";

export const DELETE_CONTRATO_REQUEST = "DELETE_CONTRATO_REQUEST";
export const DELETE_CONTRATO_SUCCESS = "DELETE_CONTRATO_SUCCESS";
export const DELETE_CONTRATO_RESET = "DELETE_CONTRATO_RESET";
export const DELETE_CONTRATO_FAIL = "DELETE_CONTRATO_FAIL";

export const CONTRATO_DETAILS_REQUEST = "CONTRATO_DETAILS_REQUEST";
export const CONTRATO_DETAILS_SUCCESS = "CONTRATO_DETAILS_SUCCESS";
export const CONTRATO_DETAILS_FAIL = "CONTRATO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
