export const ADMIN_DIRIGENTES_REQUEST = "ADMIN_DIRIGENTES_REQUEST";
export const ADMIN_DIRIGENTES_SUCCESS = "ADMIN_DIRIGENTES_SUCCESS";
export const ADMIN_DIRIGENTES_FAIL = "ADMIN_DIRIGENTES_FAIL";

export const CREATE_DIRIGENTE_REQUEST = "CREATE_DIRIGENTE_REQUEST";
export const CREATE_DIRIGENTE_SUCCESS = "CREATE_DIRIGENTE_SUCCESS";
export const CREATE_DIRIGENTE_RESET = "CREATE_DIRIGENTE_RESET";
export const CREATE_DIRIGENTE_FAIL = "CREATE_DIRIGENTE_FAIL";

export const UPDATE_DIRIGENTE_REQUEST = "UPDATE_DIRIGENTE_REQUEST";
export const UPDATE_DIRIGENTE_SUCCESS = "UPDATE_DIRIGENTE_SUCCESS";
export const UPDATE_DIRIGENTE_RESET = "UPDATE_DIRIGENTE_RESET";
export const UPDATE_DIRIGENTE_FAIL = "UPDATE_DIRIGENTE_FAIL";

export const DELETE_DIRIGENTE_REQUEST = "DELETE_DIRIGENTE_REQUEST";
export const DELETE_DIRIGENTE_SUCCESS = "DELETE_DIRIGENTE_SUCCESS";
export const DELETE_DIRIGENTE_RESET = "DELETE_DIRIGENTE_RESET";
export const DELETE_DIRIGENTE_FAIL = "DELETE_DIRIGENTE_FAIL";

export const DIRIGENTE_DETAILS_REQUEST = "DIRIGENTE_DETAILS_REQUEST";
export const DIRIGENTE_DETAILS_SUCCESS = "DIRIGENTE_DETAILS_SUCCESS";
export const DIRIGENTE_DETAILS_FAIL = "DIRIGENTE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
