export const ADMIN_INFORMACION_REQUEST = "ADMIN_INFORMACION_REQUEST";
export const ADMIN_INFORMACION_SUCCESS = "ADMIN_INFORMACION_SUCCESS";
export const ADMIN_INFORMACION_FAIL = "ADMIN_INFORMACION_FAIL";

export const CREATE_INFORMACION_REQUEST = "CREATE_INFORMACION_REQUEST";
export const CREATE_INFORMACION_SUCCESS = "CREATE_INFORMACION_SUCCESS";
export const CREATE_INFORMACION_RESET = "CREATE_INFORMACION_RESET";
export const CREATE_INFORMACION_FAIL = "CREATE_INFORMACION_FAIL";

export const UPDATE_INFORMACION_REQUEST = "UPDATE_INFORMACION_REQUEST";
export const UPDATE_INFORMACION_SUCCESS = "UPDATE_INFORMACION_SUCCESS";
export const UPDATE_INFORMACION_RESET = "UPDATE_INFORMACION_RESET";
export const UPDATE_INFORMACION_FAIL = "UPDATE_INFORMACION_FAIL";

export const INFORMACION_DETAILS_REQUEST = "INFORMACION_DETAILS_REQUEST";
export const INFORMACION_DETAILS_SUCCESS = "INFORMACION_DETAILS_SUCCESS";
export const INFORMACION_DETAILS_FAIL = "INFORMACION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
