export const ADMIN_MIEMBROS_REQUEST = "ADMIN_MIEMBROS_REQUEST";
export const ADMIN_MIEMBROS_SUCCESS = "ADMIN_MIEMBROS_SUCCESS";
export const ADMIN_MIEMBROS_FAIL = "ADMIN_MIEMBROS_FAIL";

export const GET_JUGADORES_REQUEST = "GET_JUGADORES_REQUEST";
export const GET_JUGADORES_SUCCESS = "GET_JUGADORES_SUCCESS";
export const GET_JUGADORES_FAIL = "GET_JUGADORES_FAIL";

export const GET_CUERPO_TECNICO_REQUEST = "GET_CUERPO_TECNICO_REQUEST";
export const GET_CUERPO_TECNICO_SUCCESS = "GET_CUERPO_TECNICO_SUCCESS";
export const GET_CUERPO_TECNICO_FAIL = "GET_CUERPO_TECNICO_FAIL";

export const GET_CUERPO_MEDICO_REQUEST = "GET_CUERPO_MEDICO_REQUEST";
export const GET_CUERPO_MEDICO_SUCCESS = "GET_CUERPO_MEDICO_SUCCESS";
export const GET_CUERPO_MEDICO_FAIL = "GET_CUERPO_MEDICO_FAIL";

export const CREATE_MIEMBRO_REQUEST = "CREATE_MIEMBRO_REQUEST";
export const CREATE_MIEMBRO_SUCCESS = "CREATE_MIEMBRO_SUCCESS";
export const CREATE_MIEMBRO_RESET = "CREATE_MIEMBRO_RESET";
export const CREATE_MIEMBRO_FAIL = "CREATE_MIEMBRO_FAIL";

export const UPDATE_MIEMBRO_REQUEST = "UPDATE_MIEMBRO_REQUEST";
export const UPDATE_MIEMBRO_SUCCESS = "UPDATE_MIEMBRO_SUCCESS";
export const UPDATE_MIEMBRO_RESET = "UPDATE_MIEMBRO_RESET";
export const UPDATE_MIEMBRO_FAIL = "UPDATE_MIEMBRO_FAIL";

export const DELETE_MIEMBRO_REQUEST = "DELETE_MIEMBRO_REQUEST";
export const DELETE_MIEMBRO_SUCCESS = "DELETE_MIEMBRO_SUCCESS";
export const DELETE_MIEMBRO_RESET = "DELETE_MIEMBRO_RESET";
export const DELETE_MIEMBRO_FAIL = "DELETE_MIEMBRO_FAIL";

export const MIEMBRO_DETAILS_REQUEST = "MIEMBRO_DETAILS_REQUEST";
export const MIEMBRO_DETAILS_SUCCESS = "MIEMBRO_DETAILS_SUCCESS";
export const MIEMBRO_DETAILS_FAIL = "MIEMBRO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
