export const CREATE_NOTICIA_REQUEST = "CREATE_NOTICIA_REQUEST";
export const CREATE_NOTICIA_SUCCESS = "CREATE_NOTICIA_SUCCESS";
export const CREATE_NOTICIA_RESET = "CREATE_NOTICIA_RESET";
export const CREATE_NOTICIA_FAIL = "CREATE_NOTICIA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
