export const ADMIN_NOTICIAS_REQUEST = "ADMIN_NOTICIAS_REQUEST";
export const ADMIN_NOTICIAS_SUCCESS = "ADMIN_NOTICIAS_SUCCESS";
export const ADMIN_NOTICIAS_FAIL = "ADMIN_NOTICIAS_FAIL";

export const TOP_NOTICIAS_REQUEST = "TOP_NOTICIAS_REQUEST";
export const TOP_NOTICIAS_SUCCESS = "TOP_NOTICIAS_SUCCESS";
export const TOP_NOTICIAS_FAIL = "TOP_NOTICIAS_FAIL";

export const CREATE_NOTICIA_REQUEST = "CREATE_NOTICIA_REQUEST";
export const CREATE_NOTICIA_SUCCESS = "CREATE_NOTICIA_SUCCESS";
export const CREATE_NOTICIA_RESET = "CREATE_NOTICIA_RESET";
export const CREATE_NOTICIA_FAIL = "CREATE_NOTICIA_FAIL";

export const UPDATE_NOTICIA_REQUEST = "UPDATE_NOTICIA_REQUEST";
export const UPDATE_NOTICIA_SUCCESS = "UPDATE_NOTICIA_SUCCESS";
export const UPDATE_NOTICIA_RESET = "UPDATE_NOTICIA_RESET";
export const UPDATE_NOTICIA_FAIL = "UPDATE_NOTICIA_FAIL";

export const DELETE_NOTICIA_REQUEST = "DELETE_NOTICIA_REQUEST";
export const DELETE_NOTICIA_SUCCESS = "DELETE_NOTICIA_SUCCESS";
export const DELETE_NOTICIA_RESET = "DELETE_NOTICIA_RESET";
export const DELETE_NOTICIA_FAIL = "DELETE_NOTICIA_FAIL";

export const NOTICIA_DETAILS_REQUEST = "NOTICIA_DETAILS_REQUEST";
export const NOTICIA_DETAILS_SUCCESS = "NOTICIA_DETAILS_SUCCESS";
export const NOTICIA_DETAILS_FAIL = "NOTICIA_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
