export const ADMIN_PARTIDOS_REQUEST = "ADMIN_PARTIDOS_REQUEST";
export const ADMIN_PARTIDOS_SUCCESS = "ADMIN_PARTIDOS_SUCCESS";
export const ADMIN_PARTIDOS_FAIL = "ADMIN_PARTIDOS_FAIL";

export const TOP_PARTIDO_REQUEST = "TOP_PARTIDO_REQUEST";
export const TOP_PARTIDO_SUCCESS = "TOP_PARTIDO_SUCCESS";
export const TOP_PARTIDO_FAIL = "TOP_PARTIDO_FAIL";

export const LAST_PARTIDOS_REQUEST = "LAST_PARTIDOS_REQUEST";
export const LAST_PARTIDOS_SUCCESS = "LAST_PARTIDOS_SUCCESS";
export const LAST_PARTIDOS_FAIL = "LAST_PARTIDOS_FAIL";

export const NEXT_PARTIDOS_REQUEST = "NEXT_PARTIDOS_REQUEST";
export const NEXT_PARTIDOS_SUCCESS = "NEXT_PARTIDOS_SUCCESS";
export const NEXT_PARTIDOS_FAIL = "NEXT_PARTIDOS_FAIL";

export const CREATE_PARTIDO_REQUEST = "CREATE_PARTIDO_REQUEST";
export const CREATE_PARTIDO_SUCCESS = "CREATE_PARTIDO_SUCCESS";
export const CREATE_PARTIDO_RESET = "CREATE_PARTIDO_RESET";
export const CREATE_PARTIDO_FAIL = "CREATE_PARTIDO_FAIL";

export const UPDATE_PARTIDO_REQUEST = "UPDATE_PARTIDO_REQUEST";
export const UPDATE_PARTIDO_SUCCESS = "UPDATE_PARTIDO_SUCCESS";
export const UPDATE_PARTIDO_RESET = "UPDATE_PARTIDO_RESET";
export const UPDATE_PARTIDO_FAIL = "UPDATE_PARTIDO_FAIL";

export const DELETE_PARTIDO_REQUEST = "DELETE_PARTIDO_REQUEST";
export const DELETE_PARTIDO_SUCCESS = "DELETE_PARTIDO_SUCCESS";
export const DELETE_PARTIDO_RESET = "DELETE_PARTIDO_RESET";
export const DELETE_PARTIDO_FAIL = "DELETE_PARTIDO_FAIL";

export const PARTIDO_DETAILS_REQUEST = "PARTIDO_DETAILS_REQUEST";
export const PARTIDO_DETAILS_SUCCESS = "PARTIDO_DETAILS_SUCCESS";
export const PARTIDO_DETAILS_FAIL = "PARTIDO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
