export const CREATE_PEDIDO_REQUEST = "CREATE_PEDIDO_REQUEST";
export const CREATE_PEDIDO_SUCCESS = "CREATE_PEDIDO_SUCCESS";
export const CREATE_PEDIDO_FAIL = "CREATE_PEDIDO_FAIL";

export const PEDIDOS_REQUEST = "PEDIDOS_REQUEST";
export const PEDIDOS_SUCCESS = "PEDIDOS_SUCCESS";
export const PEDIDOS_FAIL = "PEDIDOS_FAIL";

export const GET_PEDIDOS_REQUEST = "GET_PEDIDOS_REQUEST";
export const GET_PEDIDOS_SUCCESS = "GET_PEDIDOS_SUCCESS";
export const GET_PEDIDOS_FAIL = "GET_PEDIDOS_FAIL";

export const UPDATE_PEDIDO_REQUEST = "UPDATE_PEDIDO_REQUEST";
export const UPDATE_PEDIDO_SUCCESS = "UPDATE_PEDIDO_SUCCESS";
export const UPDATE_PEDIDO_RESET = "UPDATE_PEDIDO_RESET";
export const UPDATE_PEDIDO_FAIL = "UPDATE_PEDIDO_FAIL";

export const DELETE_PEDIDO_REQUEST = "DELETE_PEDIDO_REQUEST";
export const DELETE_PEDIDO_SUCCESS = "DELETE_PEDIDO_SUCCESS";
export const DELETE_PEDIDO_RESET = "DELETE_PEDIDO_RESET";
export const DELETE_PEDIDO_FAIL = "DELETE_PEDIDO_FAIL";

export const PEDIDO_DETAILS_REQUEST = "PEDIDO_DETAILS_REQUEST";
export const PEDIDO_DETAILS_SUCCESS = "PEDIDO_DETAILS_SUCCESS";
export const PEDIDO_DETAILS_FAIL = "PEDIDO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
