export const ADMIN_POSICIONES_REQUEST = "ADMIN_POSICIONES_REQUEST";
export const ADMIN_POSICIONES_SUCCESS = "ADMIN_POSICIONES_SUCCESS";
export const ADMIN_POSICIONES_FAIL = "ADMIN_POSICIONES_FAIL";

export const CREATE_POSICION_REQUEST = "CREATE_POSICION_REQUEST";
export const CREATE_POSICION_SUCCESS = "CREATE_POSICION_SUCCESS";
export const CREATE_POSICION_RESET = "CREATE_POSICION_RESET";
export const CREATE_POSICION_FAIL = "CREATE_POSICION_FAIL";

export const UPDATE_POSICION_REQUEST = "UPDATE_POSICION_REQUEST";
export const UPDATE_POSICION_SUCCESS = "UPDATE_POSICION_SUCCESS";
export const UPDATE_POSICION_RESET = "UPDATE_POSICION_RESET";
export const UPDATE_POSICION_FAIL = "UPDATE_POSICION_FAIL";

export const DELETE_POSICION_REQUEST = "DELETE_POSICION_REQUEST";
export const DELETE_POSICION_SUCCESS = "DELETE_POSICION_SUCCESS";
export const DELETE_POSICION_RESET = "DELETE_POSICION_RESET";
export const DELETE_POSICION_FAIL = "DELETE_POSICION_FAIL";

export const POSICION_DETAILS_REQUEST = "POSICION_DETAILS_REQUEST";
export const POSICION_DETAILS_SUCCESS = "POSICION_DETAILS_SUCCESS";
export const POSICION_DETAILS_FAIL = "POSICION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
