export const ADMIN_PRODUCTOS_REQUEST = "ADMIN_PRODUCTOS_REQUEST";
export const ADMIN_PRODUCTOS_SUCCESS = "ADMIN_PRODUCTOS_SUCCESS";
export const ADMIN_PRODUCTOS_FAIL = "ADMIN_PRODUCTOS_FAIL";

export const GET_PRODUCTOS_REQUEST = "GET_PRODUCTOS_REQUEST";
export const GET_PRODUCTOS_SUCCESS = "GET_PRODUCTOS_SUCCESS";
export const GET_PRODUCTOS_FAIL = "GET_PRODUCTOS_FAIL";

export const CREATE_PRODUCTO_REQUEST = "CREATE_PRODUCTO_REQUEST";
export const CREATE_PRODUCTO_SUCCESS = "CREATE_PRODUCTO_SUCCESS";
export const CREATE_PRODUCTO_RESET = "CREATE_PRODUCTO_RESET";
export const CREATE_PRODUCTO_FAIL = "CREATE_PRODUCTO_FAIL";

export const DELETE_PRODUCTO_REQUEST = "DELETE_PRODUCTO_REQUEST";
export const DELETE_PRODUCTO_SUCCESS = "DELETE_PRODUCTO_SUCCESS";
export const DELETE_PRODUCTO_RESET = "DELETE_PRODUCTO_RESET";
export const DELETE_PRODUCTO_FAIL = "DELETE_PRODUCTO_FAIL";

export const UPDATE_PRODUCTO_REQUEST = "UPDATE_PRODUCTO_REQUEST";
export const UPDATE_PRODUCTO_SUCCESS = "UPDATE_PRODUCTO_SUCCESS";
export const UPDATE_PRODUCTO_RESET = "UPDATE_PRODUCTO_RESET";
export const UPDATE_PRODUCTO_FAIL = "UPDATE_PRODUCTO_FAIL";

export const PRODUCTO_DETAILS_REQUEST = "PRODUCTO_DETAILS_REQUEST";
export const PRODUCTO_DETAILS_SUCCESS = "PRODUCTO_DETAILS_SUCCESS";
export const PRODUCTO_DETAILS_FAIL = "PRODUCTO_DETAILS_FAIL";

export const CREATE_REVISION_REQUEST = "CREATE_REVISION_REQUEST";
export const CREATE_REVISION_SUCCESS = "CREATE_REVISION_SUCCESS";
export const CREATE_REVISION_RESET = "CREATE_REVISION_RESET";
export const CREATE_REVISION_FAIL = "CREATE_REVISION_FAIL";

export const GET_REVISIONES_REQUEST = "GET_REVISIONES_REQUEST";
export const GET_REVISIONES_SUCCESS = "GET_REVISIONES_SUCCESS";
export const GET_REVISIONES_FAIL = "GET_REVISIONES_FAIL";

export const DELETE_REVISION_REQUEST = "DELETE_REVISION_REQUEST";
export const DELETE_REVISION_SUCCESS = "DELETE_REVISION_SUCCESS";
export const DELETE_REVISION_RESET = "DELETE_REVISION_RESET";
export const DELETE_REVISION_FAIL = "DELETE_REVISION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
