export const ADMIN_TIPOMIEMBROS_REQUEST = "ADMIN_TIPOMIEMBROS_REQUEST";
export const ADMIN_TIPOMIEMBROS_SUCCESS = "ADMIN_TIPOMIEMBROS_SUCCESS";
export const ADMIN_TIPOMIEMBROS_FAIL = "ADMIN_TIPOMIEMBROS_FAIL";

export const CREATE_TIPOMIEMBRO_REQUEST = "CREATE_TIPOMIEMBRO_REQUEST";
export const CREATE_TIPOMIEMBRO_SUCCESS = "CREATE_TIPOMIEMBRO_SUCCESS";
export const CREATE_TIPOMIEMBRO_RESET = "CREATE_TIPOMIEMBRO_RESET";
export const CREATE_TIPOMIEMBRO_FAIL = "CREATE_TIPOMIEMBRO_FAIL";

export const UPDATE_TIPOMIEMBRO_REQUEST = "UPDATE_TIPOMIEMBRO_REQUEST";
export const UPDATE_TIPOMIEMBRO_SUCCESS = "UPDATE_TIPOMIEMBRO_SUCCESS";
export const UPDATE_TIPOMIEMBRO_RESET = "UPDATE_TIPOMIEMBRO_RESET";
export const UPDATE_TIPOMIEMBRO_FAIL = "UPDATE_TIPOMIEMBRO_FAIL";

export const DELETE_TIPOMIEMBRO_REQUEST = "DELETE_TIPOMIEMBRO_REQUEST";
export const DELETE_TIPOMIEMBRO_SUCCESS = "DELETE_TIPOMIEMBRO_SUCCESS";
export const DELETE_TIPOMIEMBRO_RESET = "DELETE_TIPOMIEMBRO_RESET";
export const DELETE_TIPOMIEMBRO_FAIL = "DELETE_TIPOMIEMBRO_FAIL";

export const TIPOMIEMBRO_DETAILS_REQUEST = "TIPOMIEMBRO_DETAILS_REQUEST";
export const TIPOMIEMBRO_DETAILS_SUCCESS = "TIPOMIEMBRO_DETAILS_SUCCESS";
export const TIPOMIEMBRO_DETAILS_FAIL = "TIPOMIEMBRO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";