export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTRO_USUARIO_REQUEST = "REGISTRO_USUARIO_REQUEST";
export const REGISTRO_USUARIO_SUCCESS = "REGISTRO_USUARIO_SUCCESS";
export const REGISTRO_USUARIO_FAIL = "REGISTRO_USUARIO_FAIL";

export const LOAD_USUARIO_REQUEST = "LOAD_USUARIO_REQUEST";
export const LOAD_USUARIO_SUCCESS = "LOAD_USUARIO_SUCCESS";
export const LOAD_USUARIO_FAIL = "LOAD_USUARIO_FAIL";

export const UPDATE_PERFIL_REQUEST = "UPDATE_PERFIL_REQUEST";
export const UPDATE_PERFIL_SUCCESS = "UPDATE_PERFIL_SUCCESS";
export const UPDATE_PERFIL_RESET = "UPDATE_PERFIL_RESET";
export const UPDATE_PERFIL_FAIL = "UPDATE_PERFIL_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";

export const GET_USUARIOS_REQUEST = "GET_USUARIOS_REQUEST";
export const GET_USUARIOS_SUCCESS = "GET_USUARIOS_SUCCESS";
export const GET_USUARIOS_FAIL = "GET_USUARIOS_FAIL";

export const USUARIO_DETAILS_REQUEST = "USUARIO_DETAILS_REQUEST";
export const USUARIO_DETAILS_SUCCESS = "USUARIO_DETAILS_SUCCESS";
export const USUARIO_DETAILS_FAIL = "USUARIO_DETAILS_FAIL";

export const UPDATE_USUARIO_REQUEST = "UPDATE_USUARIO_REQUEST";
export const UPDATE_USUARIO_SUCCESS = "UPDATE_USUARIO_SUCCESS";
export const UPDATE_USUARIO_RESET = "UPDATE_USUARIO_RESET";
export const UPDATE_USUARIO_FAIL = "UPDATE_USUARIO_FAIL";

export const DELETE_USUARIO_REQUEST = "DELETE_USUARIO_REQUEST";
export const DELETE_USUARIO_SUCCESS = "DELETE_USUARIO_SUCCESS";
export const DELETE_USUARIO_RESET = "DELETE_USUARIO_RESET";
export const DELETE_USUARIO_FAIL = "DELETE_USUARIO_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
